CREATE TABLE RATING (
	DESCRIPTION TEXT NOT NULL, 
	FN_USER_ID INT NOT NULL,
	RATING_VALUE int NOT NULL,
	RESTAURANT_ID int NOT NULL,
	FOREIGN KEY(RESTAURANT_ID) REFERENCES RESTAURANT,
	FOREIGN KEY(FN_USER_ID) REFERENCES FN_USER 
);

ALTER TABLE FN_USER RENAME COLUMN LASTMANE TO LASTNAME

